words = [
    "aternos",
    "cgnat",
    "cloudflare",
    "configurator",
    "dearmor",
    "distros",
    "embotic",
    "fdc",
    "fumadocs",
    "jointhis",
    "lucide",
    "mymodem",
    "nmap",
    "playit",
    "simplevoicechat",
    "systemctl",
    "terraria",
    "udp",
    "ufw",
    "yoursubdomain",
]
