words = [
    # AAAA record
    "AAAA",
    # One Time Token
    "OTT",
    # SRV record
    "SRV",
    "aternos",
    # Carrier Grade Network Address Translation
    "cgnat",
    "chmod",
    "cloudflare",
    "configurator",
    "dearmor",
    "distros",
    "embotic",
    "fdc",
    "fumadocs",
    "hennion",
    "jointhis",
    "jointhisproxy",
    "joran",
    "lucide",
    "mymodem",
    "myserver",
    "nmap",
    "playit",
    "proxyserver",
    "simplevoicechat",
    "systemctl",
    "terraria",
    "tts",
    "udp",
    "ufw",
    "yoursubdomain",
]
