"use server";
import type { NextRequest } from "next/server";
import { auth, ValidateDiscordID } from "@/auth";
import { UserIdFromAvatar } from "@/auth";
import mysql, { RowDataPacket } from "mysql2/promise";

async function GetConfig(userID: string, innerTCP: string, innerUDP: string) {
  let connectionParams = {
    host: process.env.PROXYHOST,
    port: 3306,
    user: "proxy",
    password: process.env.PROXYPW,
    database: "jointhisproxy",
  };
  const connection = await mysql.createConnection(connectionParams);
  // Assign OWNER
  try {
    await connection.query(
      `UPDATE AuthenticationTokens SET OWNER = ${userID} WHERE (OWNER = ${userID} OR ISNULL(OWNER)) ORDER BY OWNER DESC LIMIT 1`,
    );
  } catch (err: any) {
    console.error(err);
    return Response.json(
      {
        error: "Unable to assign tunnel to user.",
      },
      { status: 500 },
    );
  }
  // Get Token, TCP, UDP
  try {
    type Row = {
      Token: string;
      TCP: number;
      UDP: number;
    };
    const [results, fields] = await connection.query<RowDataPacket[]>(
      `SELECT Token, TCP, UDP from AuthenticationTokens where OWNER = ${userID}`,
    );
    console.log(results);
    const authKey = results[0].Token;
    const tcp = results[0].TCP;
    const udp = results[0].UDP;
    const config = `
# Generated by JoinThis.proxy CLI
gateway_url: wss://proxy.jointhis.party
auth_key: ${authKey}
forwards:
  - port: ${tcp}/tcp
    destination: 127.0.0.1:${innerTCP}
  - port: ${udp}/udp
    destination: 127.0.0.1:${innerUDP}
`;
    return Response.json({ config: config });
  } catch (err: any) {
    return Response.json(
      {
        error: "Unable to fetch tunnel info.",
      },
      { status: 500 },
    );
  }
}

export async function GET(
  _req: NextRequest,
  ctx: RouteContext<"/api/cli/[token]/[tcp]/[udp]">,
) {
  const { token } = await ctx.params;
  const { tcp } = await ctx.params;
  const { udp } = await ctx.params;
  try {
    const data = await auth.api.verifyOneTimeToken({
      body: {
        token: token, // required
      },
    });
    const userID = UserIdFromAvatar(data?.user?.image);
    if (ValidateDiscordID.test(userID || "")) {
      return await GetConfig(userID || "", tcp, udp);
    } else {
      return Response.json(
        {
          error: "Failed to verify Discord ID",
        },
        { status: 401 },
      );
    }
  } catch (err: any) {
    return Response.json(
      {
        error: err?.body?.message,
      },
      { status: err?.statusCode },
    );
  }
}
